# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
#
# Set _CONFIGURE_FLAGS=--enable-nvcc for nvcc builds (Nvidia Systems)

timeout : 5400s
steps:

- id : Build hip-fortran
  name: 'gcr.io/cloud-builders/docker'
  args: ['build','--build-arg','CONFIGURE_FLAGS=${_CONFIGURE_FLAGS}',
                 '--build-arg','PLATFORM=${_PLATFORM}','.',
                 '-t','gcr.io/$PROJECT_ID/hip-fortran:${_PLATFORM}-${_VERSION}']

images:
- 'gcr.io/$PROJECT_ID/hip-fortran:${_PLATFORM}-${_VERSION}'

substitutions:
  _CONFIGURE_FLAGS: '--enable-nvcc'
  _PLATFORM: 'nvcc'
  _VERSION: 'latest'
