# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
#
# Set _CONFIGURE_FLAGS=--enable-nvcc for nvcc builds (Nvidia Systems)

timeout : 5400s
steps:

- id : Build hip-fortran docker image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build','-f','cloudbuild/Dockerfile','.',
                 '-t','gcr.io/$PROJECT_ID/hip-fortran:${_VERSION}']

images:
- 'gcr.io/$PROJECT_ID/hip-fortran:${_VERSION}'

substitutions:
  _VERSION: 'latest'

