# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
#

timeout : 5400s
steps:

- id : Build hip-fortran tests
  name: 'gcr.io/hip-fortran/singularity'
  args: ['build','--notest','hip-fortran-nvcc_test','nvcc_test.def']

#- id : Build hip-fortran tests (hcc)
#  name: 'gcr.io/hip-fortran/singularity'
#  args: ['build','hip-fortran-nvcc_test','hcc_test.def']

artifacts:
  objects:
    location: 'gs://hip-fortran_singularity/'
    paths: ['/workspace/hip-fortran-nvcc_test']

#substitutions:
#  _VERSION: 'latest'
